AWSTemplateFormatVersion: '2010-09-09'
Description: Database stack - RDS PostgreSQL

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - staging
      - production
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
  DBName:
    Type: String
    Default: mydatabase
  DBEngineVersion:
    Type: String
    Default: '18.4'
  DBMasterUsername:
    Type: String
    Default: masteruser
  DBSecretName:
    Type: String
    Description: Name (or full ARN) of the Secrets Manager secret containing DB credentials
    Default: practice/database/master-password
  AllocatedStorage:
    Type: Number
    Default: 20

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub ${Environment} private subnet group for RDS
      SubnetIds:
        - !Select
          - 0
          - !Split
            - ','
            - !ImportValue networking-PrivateSubnetIds
        - !Select
          - 1
          - !Split
            - ','
            - !ImportValue networking-PrivateSubnetIds
      Tags:
        - Key: Environment
          Value: !Ref Environment

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: String
      VpcId: !ImportValue networking-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Environment
          Value: !Ref Environment

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceClass: !Ref DBInstanceClass
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecretName}:SecretString:password}}'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp2
      PubliclyAccessible: false
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DBEndpoint:
    Description: RDS endpoint address
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-DBEndpoint

  DBPort:
    Description: RDS endpoint port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${AWS::StackName}-DBPort